; PHP.
(class_declaration) @container
(interface_declaration) @container
(trait_declaration) @container
(method_declaration) @callable
(function_definition) @callable
(function_call_expression) @call
(member_call_expression) @call
(object_creation_expression) @call
(namespace_use_declaration) @import
(property_declaration) @binding
(simple_parameter) @binding
(assignment_expression) @binding
